name: Run Trades v1

on:
  schedule:
     - cron: '*/7 * * * *'

jobs:
  run-scout:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://stock-market-trader.vercel.app/run-trades'
          method: 'POST'
          contentType: 'application/json'
          data: '{"password": "${{ secrets.TRADES_PASSWORD }}"}'